name: thumbor
description: A Thumbor client for Dart. Use this to generate generate the URLs to communicate to your Thumbor service
version: 1.0.4
homepage: https://github.com/QuirijnGB/thumbor

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
