name: thumbor
description: A Thumbor client for Dart
version: 0.0.1
author: Quirijn Groot Bluemink <quirijn.grootbluemink@gmail.com>
homepage: https://github.com/QuirijnGB/thumbor

environment:
  sdk: '>=2.0.0-dev.1.2 <2.0.0'

dependencies:
  crypto: ^2.0.5

dev_dependencies:
  test: ^1.2.0

