name: thumbor
description: A Thumbor client for Dart. Use this to generate generate the URLs to communicate to your Thumbor service
version: 0.0.4
author: Quirijn Groot Bluemink <quirijn.grootbluemink@gmail.com>
homepage: https://github.com/QuirijnGB/thumbor

environment:
  sdk: '>=2.0.0-dev.1.2 <3.0.0'

dependencies:
  crypto: ^2.0.0

dev_dependencies:
  test: ^1.3.0

